notify:
  enable: true
  sender_email: email@<senderdomain>.com
  sender_name: "Air Monitor Service"
  to:
    - email@<receiverdomain>.com

valleywater:
  watershed: Guadalupe

baaqmd:
  authkey: your_auth_key
  zones:
    - name: "Santa Clara Valley"
      station_ids:
        - 7032
