notify:
  enable: true
  to:
    - email@<somedomain>.com

valleywater:
  watershed: Guadalupe

baaqmd:
  authkey: your_auth_key
  zones:
    - name: "Santa Clara Valley"
      station_ids:
        - 7032
